BlogFront/urls.py
# -*- coding: utf-8 -*-
"""
 @Time    : 2018/3/13 16:50
 @Author  : CyanZoy
 @File    : urls.py
 @Software: PyCharm
 """
from django.urls import path
from BlogFront import views


urlpatterns = [

    path('register.html', views.register),
    path('register', views.register),
    path('login', views.login_process),
    path('login.html', views.login_process),
    path('note', views.note),
    path('logout', views.logout_process),
    path('', views.index),

]

Wx/urls.py
from django.urls import path
from Wx import views


urlpatterns = [
    path('', views.wx_authentication),
]

BlogFront/models.py
from django.db import models


class NoteName(models.Model):
    """
    @ Create by CyanZoy on 2018/3/24 16:07
    @ Describe: 用来存放不同笔记名
    """
    name = models.CharField('笔记本名', max_length=255, default=None)
    creat_time = models.DateTimeField('创建时间', auto_now_add=True)

    class Meta:
        # verbose_name = '笔记本'
        verbose_name_plural = '笔记本'
        app_label = 'BlogFront'


class NoteT(models.Model):
    """
    @ Create by CyanZoy on 2018/3/24 16:14
    @ Describe: 用来存放笔记-
    """
    # 此条笔记的编号
    note_num = models.CharField(max_length=150)
    note_user = models.CharField(max_length=255, default=None)
    creat_time = models.DateTimeField(auto_now_add=True)
    note_title = models.CharField(max_length=255, default=None)
    note_label = models.CharField(max_length=20, default=None)
    belong = models.ForeignKey(NoteName, related_name='belong_name', on_delete=models.SET_NULL, null=True)


class NoteInfo(models.Model):
    # 笔记编号
    note_info_num = models.CharField(max_length=150)
    # 笔记顺序号
    note_info_sign = models.IntegerField()
    # 笔记的标题
    note_info_title = models.CharField(max_length=100, default=None)
    # 笔记的代码片
    note_info_code = models.TextField()
    # 笔记的图片路径
    note_info_img = models.CharField(max_length=50, default=None)

BlogFront/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import (login, logout, authenticate,)
from django import forms
from django.contrib.auth.decorators import login_required
import json
from collections import defaultdict


class UserRegisterFrom(forms.Form):
    username = forms.CharField(label="用户名", max_length=100, min_length=3,
                               widget=forms.TextInput(attrs={'autofocus': 'autofocus', 'placeholder': '请输入用户名',
                                                             'name': 'form_username',
                                                             'class': 'form-first-name form-control'}))
    password = forms.CharField(label='密码', min_length=6,
                               widget=forms.TextInput(attrs={'placeholder': '请输入密码', 'name': 'form_password',
                                                             'class': 'form-first-name form-control',
                                                             'type': 'password'}))

    password_again = forms.CharField(label='密码', min_length=6,
                               widget=forms.TextInput(attrs={'placeholder': '请再次输入密码', 'name': 'form_password_again',
                                                             'class': 'form-first-name form-control',
                                                             'type': 'password'}))


class UserLoginFrom(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class roo(forms.Form):
    msg = forms.CharField(
        label='wrong',
    )


def index(request):
    return render(request, 'htmls/index.html')


def login_process(request):
    __next_web = request.GET.get('next') if request.GET.get('next') else '/note'
    print(__next_web)
    if request.method == "POST":
        uf_login = UserLoginFrom(request.POST)
        if uf_login.is_valid():
            username = uf_login.cleaned_data['username']
            password = uf_login.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                request.session['username'] = username
                response = HttpResponseRedirect(__next_web)
                request.session.set_expiry(60*15)
                return response
            else:
                return HttpResponseRedirect('/login')
    elif request.user.is_authenticated:
        return HttpResponseRedirect('/note')
    else:
        uf = UserRegisterFrom()
        return render(request, 'htmls/login.html', {'uf': uf, 'next': __next_web})


def logout_process(request):
    logout(request)
    return HttpResponseRedirect('/')


def register(request):
    if request.method == 'POST' and not request.is_ajax():
        newUser = UserRegisterFrom(request.POST)
        if newUser.is_valid():
            username = newUser.cleaned_data['username']
            password = newUser.cleaned_data['password']
            password_again = newUser.cleaned_data['password_again']
            return HttpResponseRedirect('/')
        else:
            g = newUser.errors.as_json()
            print(g)
            msg = []
            for _ in newUser.errors:
                print(newUser.errors[_].data[0])
                msg.append(newUser.errors[_].data[0])
            uf = UserRegisterFrom()
            return render(request, 'htmls/register.html', {'msg': msg, 'uf': uf})
    elif request.method == 'POST' and request.is_ajax():
        username = request.POST.get('username')
        print(username)
        return HttpResponse("yes")
    else:
        uf = UserRegisterFrom()
        context = {'uf': uf}
        return render(request, 'htmls/register.html', context)


from BlogFront.interface.note_model import *
@login_required
def note(request):
    if not request.is_ajax():
        notename = request.GET.get('spm').lower()
        allname = ModelGet.note_get_name()
        # 如果没有笔记名参数则默认查询全部
        if not notename:
            allnote = ModelGet.note_get_t()
            context = Change.queryset_to_dic((allnote, allname), one='note', two='name')
            return render(request, 'htmls/note.html', context=context)
        result = ModelGet.note_get_t(notename)
        # 查询没结果则重定向至note
        if not result:
            return HttpResponseRedirect('/note')
        # 查询对应笔记
        context = Change.queryset_to_dic((result, allname), one='note', two='name')
        return render(request, 'htmls/note.html', context=context)
    else:
        # spm = notename = request.GET.get('spm').lower()
        note_num = request.GET.get('id')
        print(note_num)
        return HttpResponse('success')

BlogFront/templates/htmls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="login.html">登录</a>
<a href="register.html">去注册</a>
</body>
</html>

BlogFront/templates/htmls/login.html
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap Modal Registration Form Template</title>

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="/static/assets/css/form-elements.css">
        <link rel="stylesheet" href="/static/assets/css/style.css">

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="../../static/assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/static/assets/ico/apple-touch-icon-57-precomposed.png">
        <style>
            body,html{
                height: 100%;
                width: 100%;
            }
            .kj{
                width: 100%;
                transition: opacity .15s;
                position: absolute;top: 50%;
                transform: translate(-50%, -50%);
                display: inline-block;
            }

        </style>
    </head>

    <body>

        <!-- MODAL -->
        <div style="position: relative;height: 100%;width: 100%">
            <form action="login?next={{next}}" method="post">
                <div class="kj" id="modal-register" tabindex="-1" role="dialog" aria-labelledby="modal-register-label" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                                </button>
                                <h3 class="modal-title" id="modal-register-label">登录</h3>
                                <p>请填写下面的表格</p>
                            </div>

                            <div class="modal-body">

                                <form role="form" action="" method="post" class="registration-form">
                                    <div class="form-group">
                                        <label class="sr-only" for="form-username">用户名</label>
                                        {{uf.username}}
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">密码</label>
                                        {{uf.password}}
                                    </div>
                                    <button type="submit" class="btn">GO!</button>
                                </form>

                            </div>

                        </div>
                    </div>
                </div>
            </form>
            
        </div>


        <!-- Javascript -->
        <script src="/static/assets/js/jquery-1.11.1.min.js"></script>
        <script src="/static/assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/assets/js/jquery.backstretch.min.js"></script>
        <script src="/static/assets/js/scripts.js"></script>

        <!--[if lt IE 10]>
            <script src="/static/assets/js/placeholder.js"></script>
        <![endif]-->

    </body>

</html>

BlogFront/templates/htmls/note.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
<title>title</title>
<link rel="stylesheet" href="/static/Note/bootstrap/css/bootstrap.css">
<link rel="stylesheet" href="/static/Note/bootstrap/css/style.css">
<link rel="stylesheet" href="/static/Note/bootstrap/css/animate.css">

<style>
    pre{
        margin-top: .5rem;
    }
</style>
</head>
<body style="position: static; overflow: visible;">
<div class="app">
	<div class="left-container">
		<div class="left-layout-container pc">
			<!--左边导航-->
			<div data-v-007cfd86="" class="user-info"><img data-v-007cfd86="" src="https://www.cyanzoy.top/images-service/touxiang.jpg"> 
				<div data-v-007cfd86="" class="login-name">CyanZoy</div> 
				<div data-v-007cfd86="">努力是可以超越天才的</div>
			</div>
<!--
			<ul data-v-007cfd86="" class="other-site">
				<li data-v-007cfd86=""><img data-v-007cfd86="" src="static/img/github.png"></li>
				<li data-v-007cfd86=""><img data-v-007cfd86="" src="static/img/weibo.png"></li>
			</ul>
-->
			<ul data-v-007cfd86="" class="left-menu">
				<li data-v-007cfd86="" class="selected-menu">个人博客</li> 
<!--				<li data-v-007cfd86="" class="">前端导航</li> -->
				<li data-v-007cfd86="" class="">关于我</li>
			</ul>				
		</div>
		<div class="navbar">
			<!--手机顶部导航-->
			<nav>
				<a class="return">
					<i class="icon-directory">
						<span class="glyphicon glyphicon-user" id="user-icon"></span>
					</i>
				</a> 
			<h1 class="nav_title"><p >CyanZoy</p></h1> 
			<div class="nav_r">
				<a href="javascript:;">
					<i class="icon-search"></i>
				</a>
			</div>
			</nav>
		</div>	
		<div class="left-user mobile">
			<!-- <div class="left-layout-container">
				<div class="user-info">
					<img src="https://www.cyanzoy.top/images-service/touxiang.jpg">
					<div class="login-name">CyanZoyss</div> 
					<div>努力……</div>
				</div> 
				<ul class="left-menu">
					<li class="router-link-exact-active router-link-active selected-menu">个人博客</li>
					<li class=""><a href="">关于我</a></li>
				</ul>
				<div class="copyright">1099312914@qq.com</div>
			</div>
			<div class="left-layout-bg">				
			</div> -->
		</div>
	</div>
	<div class="blog-container main-container" style="background-color: white">
		<!--右部内容-->
	  <ul class="label-list">
			<li><span class="tag" style="background-color: rgb(53, 147, 242);"><a href="/note">ALL</a></span></li>
			{% for i in name %}
                <li><span class="tag tag-unchecked"><a href="/note?spm={{ i.name }}">{{ i.name }}</a></span></li>
            {% endfor %}

	  </ul>
		 <div class="blog-detail-container" style="display: none">
	  		<!--详情页-->
		  <div class="title-container">
			<span class="title" id="title">Python-scrapy安装报错No module named _sqlite3</span>
			<ul>
			 <li class="tag tag-small" style="background-color: rgb(194, 224, 198);">webpack </li>
			</ul> 
			<span class="back"><img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxOCIgaGVpZ2h0PSIxMiIgdmlld0JveD0iMCAwIDE4IDEyIj4NCiAgICA8ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPg0KICAgICAgICA8cGF0aCBkPSJNLTMtNmgyNHYyNEgtM3oiLz4NCiAgICAgICAgPHBhdGggZmlsbD0iIzRCNTk1RiIgZmlsbC1ydWxlPSJub256ZXJvIiBkPSJNMTggNUgzLjgzbDMuNTgtMy41OUw2IDAgMCA2bDYgNiAxLjQxLTEuNDFMMy44MyA3SDE4eiIvPg0KICAgIDwvZz4NCjwvc3ZnPg0K" class="back-icon" />返回 </span>
		  </div> 
		  <div class="comment-container bga-back-top">
			<div class="comment">
			 <div class="comment-title">
			 <div>
			  <img src="https://www.cyanzoy.top/images-service/touxiang.jpg"/> 
			  <span>CyanZoy</span>
			 </div> 
			 <span class="time" id="time">2018-01-09 11:58</span>
			 </div> 
			 <article class="comment-body markdown-body">
				<h3>解决No module named _sqlite3的问题</h3>
				<h3>出错源头：使用scrapy bench 测试命令时报错</h3> 
				<pre><code>1，首先安装 sqlite-devel<br>yum install sqlite-devel<br>2，重新编译安装Python<br>./configure --prefix=/usr/local/python/python3<br>make<br>make install</code>
				</pre> 
			 </article>
            <article class="comment-body markdown-body">
                <h3>解决No module named _sqlite3的问题</h3>
                <h3>出错源头：使用scrapy bench 测试命令时报错</h3>
                <pre><code>1，首先安装 sqlite-devel<br>yum install sqlite-devel<br>2，重新编译安装Python<br>./configure --prefix=/usr/local/python/python3<br>make<br>make install</code>
                </pre>
            </article>
			</div> 			
		  </div>
		 </div> 
	  <div class="blog-list-container">
		<div class="table-header">
			<span >名称</span> 
			<span >创建时间</span>
		</div> 
		<ul class="issue-list">
		 <li class="issue-item"><a href="javascript:void(0)" class="" id="test"> Python-scrapy安装报错No module named _sqlite3 </a> 
			 <ul><li class="tag tag-small" style="background-color: rgb(14, 138, 22);">Scrapy</li></ul> 
			 <span class="time"> 2017-12-28 11:44 </span>
		 </li>
            {% for i in note %}
                <li class="issue-item"><a href="javascript:void(0)" class="" id="{{ i.note_num }}"> {{ i.note_title }} </a>
                    <ul><li class="tag tag-small" style="background-color: rgb(14, 138, 22);">{{ i.note_label }}</li></ul>
                    <span class="time {{ i.note_num }}"> {{ i.creat_time }} </span>
                </li>
            {% endfor %}
		</ul>

		
		<div class="bottom-bar">
			<input type="text" placeholder="按文章标题或内容搜索..." class="fl query" /> 
		 <div  class="paginataion-container">
			<span class="total-num">共&nbsp;51&nbsp;条</span> 
			<img class="pre-page-disabled" /> 
			<input type="number" class="current-page" /> 
			<span class="page-count">/&nbsp;&nbsp;&nbsp;6</span> 
			<img class="next-page" />
		 </div>
		</div>
	  </div>
	</div>
	<!--右部内容over-->	
</div>

<script src="/static/Note/bootstrap/js/jquery-3.2.1.min.js"></script>
<!--<script src="bootstrap/js/bootstrap.min.js"></script>-->
{#<script>#}
{#var homeUrl = ""#}
{#//获取项目路径#}
{#$(function(){#}
{#	var pathName = window.document.location.pathname;#}
{#	homeUrl = pathName.substr(0, pathName.substring(1).indexOf('/')+1)#}
{#{)#}
{#</script>#}
<script>
    $('.back').click(function(){
        $(".blog-detail-container").css("display", "none");
        $(".blog-list-container").css('display', 'flex');
    });
    {#详情页#}
    var info = $('.blog-detail-container');
    $('.issue-item a').click(function(){
        console.log($(this).attr('id'));
        $('#title').html($(this).html());
        var id = $(this).attr('id');
        $("#time").html($("."+id+"").html());
        get_info(id);
        $(".blog-detail-container").css("display", "block");
        $(".blog-list-container").css('display', 'none');
    });
    function get_info(note_num){
        $.ajax({
            url:'/note?id='+note_num+'',
            type:'GET',
            success:function(data){
                console.log(data)
            }
        })
    }
</script>
<script>
	$(function(){
		$("#test").click(function(){
			$(".blog-detail-container").css("display", "block");
			$(".blog-list-container").remove()			
		});
		var mobile_info = '<div class="left-layout-container animated fadeInLeft">'+
							'<div class="user-info">'+
								'<img src="https://www.cyanzoy.top/images-service/touxiang.jpg">'+
								'<div class="login-name">CyanZoy</div> '+
								'<div>努力……</div>'+
							'</div> '+
							'<ul class="left-menu">'+
								'<li class="router-link-exact-active router-link-active selected-menu">个人博客</li>'+
								'<li class=""><a href="">关于我</a></li>'+
							'</ul>'+
							'<div class="copyright">1099312914@qq.com</div>'+
						'</div>'+
						'<div class="left-layout-bg">'+
						'</div>';
		$(".icon-directory").click(function(){
			$(".mobile").append(mobile_info);
		});
		$('.mobile .left-layout-container, .icon-directory').click(function (event) {  
			event.stopPropagation();
			return false;
		});  
		$(document).click(function(event){
		    var a = $(".mobile .left-layout-container");
			if (!a.hasClass('fadeInLeft')){
				return;
			}
			var _con = a;   // 设置目标区域
			if(!_con.is(event.target) && _con.has(event.target).length === 0){				  
				a.removeClass('animated fadeInLeft');
				a.addClass('animated slideOutLeft');
				$(".mobile .left-layout-bg").addClass('animated fadeOut')
				setTimeout(function(){
					$(".mobile").children().remove();
				},1000)		
			}
		});
		var selected = $(".left-menu li.selected-menu");
		var se = $(".left-menu li");
		se.mouseover(function(){
{#			var se = $(".left-menu li.selected-menu");#}
			$(selected).removeClass("selected-menu");
			$(this).addClass("selected-menu");
		});
		se.mouseout(function(){
			$(this).removeClass("selected-menu");
			$(selected).addClass("selected-menu");
		});		
	})
</script>
<script>
{#	$(function(){#}
{#		$.ajax({#}
{#			url:homeUrl+"http://www.cyanzoy.top/myBlog/shiro/note/list.do",#}
{#			type:'GET',#}
{#			dataType:'json',#}
{#			success:function(data){#}
{#				for(i=0; i<data.length; i++){#}
{#					produceList(data[i].noteId, data[i].noteTitle, data[i].noteLabel, data[i].noteTime)#}
{#				}#}
{#			}#}
{#		})#}
{#	});#}
{#	#}
</script>
</body>
</html>

BlogFront/templates/htmls/register.html
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap Modal Registration Form Template</title>

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="/static/assets/css/form-elements.css">
        <link rel="stylesheet" href="/static/assets/css/style.css">

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="../../static/assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/static/assets/ico/apple-touch-icon-57-precomposed.png">
        <style>
            .input_error{
                border:solid red 1px !important;
            }

        </style>
    </head>

    <body>

        <!-- Content -->
        <div class="top-content">

            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                        	<a class="logo" href="register.html"></a>
                            <h1><strong>Blog</strong> Registration</h1>
                            <div class="description">
                            	<p>
	                            	注册博客账号，开启!
                            	</p>
                            </div>
                            <div class="top-big-link">
                            	<a class="btn btn-link-1 launch-modal" href="#" data-modal-id="modal-register">注册</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <!-- MODAL -->
        <div class="modal fade" id="modal-register" tabindex="-1" role="dialog" aria-labelledby="modal-register-label" aria-hidden="true">
        	<div class="modal-dialog">
        		<div class="modal-content">

        			<div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal">
        					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        				</button>
        				<h3 class="modal-title" id="modal-register-label">注册</h3>
        				<p>请填写下面的表格</p>
        			</div>

        			<div class="modal-body">

	                    <form role="form" action="register " onsubmit="return f()" method="post" class="registration-form">
                            <div class="form-group">
                                <label class="sr-only" for="form-username">用户名</label>
                                {{uf.username}}
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">密码</label>
                                {{uf.password}}
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password-again">密码again</label>
                                {{uf.password_again}}
                            </div>
                            <div class="form-group">
                                <label style="width: 100%;color: red; font-weight: 100; text-align: center" id="id_error"></label>
                            </div>
{#	                    	<div class="form-group">#}
{#	                    		<label class="sr-only" for="form-first-name">First name</label>#}
{#	                        	<input type="text" name="form-first-name" placeholder="First name..." class="form-first-name form-control" id="form-first-name">#}
{#	                        </div>#}
{#	                        <div class="form-group">#}
{#	                        	<label class="sr-only" for="form-last-name">Last name</label>#}
{#	                        	<input type="text" name="form-last-name" placeholder="Last name..." class="form-last-name form-control" id="form-last-name">#}
{#	                        </div>#}
{#	                        <div class="form-group">#}
{#	                        	<label class="sr-only" for="form-email">Email</label>#}
{#	                        	<input type="text" name="form-email" placeholder="Email..." class="form-email form-control" id="form-email">#}
{#	                        </div>#}
{#	                        <div class="form-group">#}
{#	                        	<label class="sr-only" for="form-about-yourself">About yourself</label>#}
{#	                        	<textarea name="form-about-yourself" placeholder="About yourself..." #}
{#	                        				class="form-about-yourself form-control" id="form-about-yourself"></textarea>#}
{#	                        </div>#}
	                        <button type="submit" class="btn" onclick="">注册！！！！</button>
	                    </form>

        			</div>

        		</div>
        	</div>
        </div>


        <!-- Javascript -->
        <script src="/static/assets/js/jquery-3.2.1.min.js"></script>
        <script src="/static/assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/assets/js/jquery.backstretch.min.js"></script>
        <script src="/static/assets/js/scripts.js"></script>

        <script>
            var p1 = $('#id_password');
            var p2 = $('#id_password_again');
            var n1 = $('#id_username');
            $(function() {
                $('#id_password, #id_password_again').focus(function(){
                    $('#id_error').html('')
                });
                $('#id_username').blur(function(){
                    $.ajax({
                        url: 'register',
                        type: 'POST',
                        data: {"username": n1.val()},
                        success: function(data){
                            console.log(data)
                        }
                    })
                })
            });
            function f(){
                if(p1.val() && p2.val() && p1.val() === p2.val()){
                    return true
                }else{
                    var count = 0;
                    if(!count) {
                        var p3 = $('#id_error');
                        timer = setInterval(function () {
                            p1.addClass("input_error");
                            p2.addClass("input_error");
                            p3.html('密码不同');
                            setTimeout(function(){
                                p1.removeClass("input_error");
                                p2.removeClass("input_error");
                            }, 250);
                            count ++;
                            if(count>2)clearInterval(timer)
                        }, 400)
                    }
                    return false
                }
            }


        </script>
    </body>

</html>